### PR TITLE
Use label selectors to filter Kubernetes pods

### PR DESCRIPTION
**Pull request by TManhente**
Issue #162 

Replaces config `k8s_app_label` with `k8s_dn_label_selector` to allow the use of Kubernetes [label selector](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors) for more flexible K8s deployments.

The old `k8s_app_label` is still supported for backward-compatibility.

Creates the test case `K8sListDnTest` to test both configs. This test case requires `kubectl` to be available and creates dummy namespaces and pods to setup the test environment.

### CODE REVIEW

**Review by jreadey — APPROVED** [review]

**Comment by jreadey** [comment]
Could you fix the flak8 errors listed here: https://github.com/HDFGroup/hsds/runs/7907409516?check_suite_focus=true? 
Thanks!

**Comment by jreadey** [comment]
Looks like the k8s_label_selector_test is being picked up by pytest and failing since we aren't testing with kubernetes currently -- see: https://github.com/HDFGroup/hsds/runs/8041629026?check_suite_focus=true#step:7:89.

I'd suggest just putting a: `@pytest.mark.skip(reason="no automated testing for kubernetes currently")` in the first lie of the test program.  Can run this manually to verify code.

**Comment by TManhente** [comment]
> I'd suggest just putting a: `@pytest.mark.skip(reason="no automated testing for kubernetes currently")` in the first lie of the test program. Can run this manually to verify code.

Done it in commit [431415c](https://github.com/HDFGroup/hsds/pull/163/commits/431415ca429e49242f4d6bb0b1072c50e119025c). I've used `@unittest.skip` instead of `@pytest.mark.skip`, as all tests within the `tests` folder seem to use `unittest`. I've put it in the test class declaration.

**Review by jreadey — APPROVED** [review]
Looks good!

**Pull request merged**
